### ISSUE TITLE
Changing Reaction forward template

### ISSUE THREAD

**Issue by atharvapurdue** [rxn4chemistry/rxn_yields#2]
How to make a reaction template to use the bert model for a different dataset

**Comment by pschwllr** [comment]
Depends on the data set, but what you could do is to atom-map some of the reactions with http://rxnmapper.ai (https://github.com/rxn4chemistry/rxnmapper). 
-> https://chemrxiv.org/articles/Unsupervised_Attention-Guided_Atom-Mapping/12298559

Then extract the templates with the tools by Thakkar et al. / Coley et al. (https://github.com/reymond-group/CASP-and-dataset-performance). 
-> https://pubs.rsc.org/en/content/articlelanding/2019/sc/c9sc04944d#!divAbstract and https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00286

The resulting templates might need some additional modifications but are a good starting point.
