### ISSUE TITLE
Can‘t find the Sukuzi-Miyaura data in the folder 'random_splits'

### ISSUE THREAD

**Issue by lry124** [rxn4chemistry/rxn_yields#6]
The code is : df = pd.read_csv(f'../data/Suzuki-Miyaura/random_splits/{name}.tsv', sep='\t')
but But in folder data/Suzuki-Miyaura/random_splits/, there is only file .gitkeep

**Comment by pschwllr** [comment]
Hi! If you ran the code in https://github.com/rxn4chemistry/rxn_yields/blob/master/nbs/01_data.ipynb, it would generate the 10 random splits. 

As others might also run into the same issue, I have added the files to the `data/Suzuki-Miyaura/random_splits` folder.
