### ISSUE TITLE
Problem with reproducing Suzuki-Miyaura results

### ISSUE THREAD

**Issue by Nanotekton** [rxn4chemistry/rxn_yields#7]
Hi! I've successfully trained from scratch the Buchwald model with your training/evaluation scripts. However, in the case of Suzuki reaction I'm getting negative R2, the model seems to not learn at all. Could you confirm the hyperparameters provided are correct? (the data should be ok, as I was able to get nice results with saved models downloaded from this repo).

As a side note: what's the meaning of '~' in SMILES representation of Pd complexes? Buchwald dataset suggest sth like a coordination bond, however, in the Suzuki dataset it resembles more a special separator. I think it was in described in some paper, but I couldn't find it.

**Comment by Nanotekton** [comment]
I guess I found a solution, though it's counterintuitive. In `training_scripts/launch_suzuki_miyaura_training.py`, parameter `"evaluate_during_training"` in `model_args` (line 87) should be set to `True`.

However, my question about the meaning of tilde is still open.

**Comment by pschwllr** [comment]
I agree, it's counterintuitive but I'm glad you found a solution. 

In the **Buchwald dataset**, the aim was to describe the original catalyst structure (Ahneman et al., Science 360, 186–190 (2018)):
<img width="319" alt="image" src="https://user-images.githubusercontent.com/38880871/121306432-1f2a1780-c8ff-11eb-8b3b-86d56c36f107.png">
The tricky part is the Nitrogen atom (RDKit will raise an exception if the explicit valence is 4). 
![image](https://user-images.githubusercontent.com/38880871/121306036-ab880a80-c8fe-11eb-85bf-774d651a5010.png)
I've seen that the canonical version of that SMILES generated by RDKit results in:
![image](https://user-images.githubusercontent.com/38880871/121306733-7e882780-c8ff-11eb-8e12-0ad2b26b668e.png)
Hence, this choice was not ideal. Now, I would probably go for another catalyst representation like: `O=S(=O)(O[Pd-]1[NH2+]C2C=CC=CC=2C2C=CC=CC1=2)C(F)(F)F`
![image](https://user-images.githubusercontent.com/38880871/121307098-ecccea00-c8ff-11eb-85cb-fd7be810e42f.png)

Anyhow, I would not expect this to significantly change the performance of the models.

For the **Suzuki dataset**, the `~` in  `CC(=O)O~CC(=O)O~[Pd]` is used as fragment group bond to keep the "Pd(OAc)2" compound together in the reaction string. We introduced this fragment group bond in [Predicting retrosynthetic pathways using transformer-based models and a hyper-graph exploration strategy](https://pubs.rsc.org/en/content/articlelanding/2020/SC/C9SC05704H#!divAbstract). We discuss it in the SI of that article.

**Comment by Nanotekton** [comment]
Thanks, now I know everything I wanted. Closing issue.
